### ISSUE TITLE
Input behaves weird on latest Firefox

### ISSUE THREAD

**Issue by binarykitchen** [seethroughtrees/react-ux-password-field#15]
When I attempt to type `123` then it types `231`. This only for the first time, all other entries work fine.

Doesn't happen on Chrome nor IE, only on FF. Somehow it moves the cursor back to the beginning after the first keypress event.

When I use another React input component, it works fine, so I guess it must be related to this package ...

**Comment by binarykitchen** [comment]
I have narrowed this down: this has something to do with this debouncer:

```
        if (this.props.toggleMask) {
          this.maskPassword = debounce(this.addPasswordType, this.props.unMaskTime);
        }
```

**Comment by binarykitchen** [comment]
Looks like cursor position changes when password type changes:
https://github.com/facebook/react/issues/4191

**Comment by seethroughdev** [comment]
Will reopen if issue requires code update.

**Comment by seethroughdev** [comment]
Reopening in reference to the PR and discussion.

**Comment by seethroughdev** [comment]
Fixed in https://github.com/seethroughtrees/react-ux-password-field/releases/tag/0.9.9

Let me know if you see any issues.

**Comment by binarykitchen** [comment]
yes, it's solved and good now. thx for fixing.

**Comment by thomasbottonari** [comment]
I am still seeing this issue in v0.9.12. I'm using Firefox v42.0...

**Comment by gordonk** [comment]
Also seeing issue in v0.9.12 Firefox v47
